### PR TITLE
Rewrite Free-Text Search extension (fixes #3, #5, #6)

### LINKED ISSUE #3: This extension could be used also for collections-search
It would be useful to have the same extension also for collections-search. See [related issue](https://github.com/stac-api-extensions/collection-search/issues/6).

### LINKED ISSUE #5: Split into multiple conformance classes?
Not all implementations may support the full suite of capabilities (e.g. not "and/or" and not "+/-" and not "exact"). I'm wondering whether it would be okay to split this into multiple conformance classes or so?

### LINKED ISSUE #6: Align with OGC API - Records
Ideally, we'd align with the `q` parameter defined by OGC APIs:
https://docs.ogc.org/DRAFTS/20-004.html#core-query-parameters-q
I'm not sure what's required for this, but just want to leave this here as a potential todo.

### PR DESCRIPTION
**Pull request by m-mohr**
It proposes to split the free text search into two parts: Basic and Advanced. (Fixes #5)
Basic implements search is based on OGC API - Records. (Fixes #6)
Advanced implements the "old" way as defined by cedadev.

It defines the q parameter not only for Item Search, but also for Collection Search and the Features endpoints. (Fixes #3)

It updates the conformace classes slightly (version number, name). It also removes the swagger files, not sure what they are here for?

@agstephens Please let me know what you think.

### CODE REVIEW

**Review by rhysrevans3 — APPROVED** [review]

**Comment by agstephens** [comment]
Thanks @m-mohr and @rhysrevans3

**Comment by chiarch84** [comment]
Dear @m-mohr @agstephens and @rhysrevans3 I would like to implement this Free Text Search in our STAC API implementation, but I cannot find anywhere the conformance class https://api.stacspec.org/v1.0.0-rc.1/collection-search
How am I supposed to implement it? Should I follow what defined [here](https://github.com/cedadev/stac-freetext-search?tab=readme-ov-file#http-get)?

My main objective is to implement it and make it work through the STAC Browser. Do I need to do something specific to make it work from there? I would like to be able to search for a specifc text and that the browser shows me all collections with that term.
Thanks for your help!

**Comment by m-mohr** [comment]
Conformance classes are either https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text or https://api.stacspec.org/v1.0.0-rc.1/collection-search#advanced-free-text depending on which variant you implement. STAC Browser supports https://api.stacspec.org/v1.0.0-rc.1/collection-search#free-text

See also https://github.com/stac-api-extensions/collection-search/pull/11
Work has stopped there due to lack of funding.

**Comment by chiarch84** [comment]
So I can add these conformance classes even if in fact they do not exist, is that correct? Since if I click  on their link I get File Not Found.

**Comment by m-mohr** [comment]
Conformance classes usually don't resolve.

**Pull request merged**
